//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnosoftModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admission
    {
        public int Id { get; set; }
        public int InstituteId { get; set; }
        public int CourseId { get; set; }
        public int BatchId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string IdentityProof { get; set; }
        public Nullable<int> LanguageOfStudy { get; set; }
        public Nullable<int> FacultyID { get; set; }
        public string NameOnCertificate { get; set; }
        public Nullable<System.DateTime> AdmissionDate { get; set; }
        public Nullable<int> InstallmentMode { get; set; }
        public Nullable<decimal> TotalFees { get; set; }
        public Nullable<decimal> TotalPaid { get; set; }
        public Nullable<decimal> TotalBalance { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<bool> IsComplete { get; set; }
        public Nullable<int> ComboCourseId { get; set; }
        public Nullable<bool> IsComboCourseStudent { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
    }
}
