//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnosoftModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComboCourseSubject
    {
        public int Id { get; set; }
        public int InstituteId { get; set; }
        public int ComboCourseId { get; set; }
        public int SubCourseId { get; set; }
        public bool IsDeleted { get; set; }
    }
}
