//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnosoftModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseFeeStructure
    {
        public int Id { get; set; }
        public int CourseFeeId { get; set; }
        public int CourseId { get; set; }
        public int Installment { get; set; }
        public decimal InstallmentAmount { get; set; }
    
        public virtual CourseFee CourseFee { get; set; }
    }
}
