//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnosoftModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enquiry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Enquiry()
        {
            this.FollowupHistories = new HashSet<FollowupHistory>();
        }
    
        public int Id { get; set; }
        public int InstituteId { get; set; }
        public int StudentId { get; set; }
        public int CourseId { get; set; }
        public int FacultyId { get; set; }
        public string Reference { get; set; }
        public System.DateTime DateAndTime { get; set; }
        public Nullable<int> FollowUpDays { get; set; }
        public string FollowUpPreferedTime { get; set; }
        public string FollowUpDescription { get; set; }
        public bool ConvertedToAdmission { get; set; }
        public bool IsClosed { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FollowupHistory> FollowupHistories { get; set; }
    }
}
