//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnosoftModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeReceipt
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public int BatchId { get; set; }
        public Nullable<int> Installment { get; set; }
        public decimal Paid { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string ModeOfPayment { get; set; }
        public int ReceivedBy { get; set; }
        public System.DateTime ReceivedDate { get; set; }
        public string UTR_ChequeNo { get; set; }
        public Nullable<System.DateTime> Transactio_ChequeDate { get; set; }
        public string CustomerDetail_BankName { get; set; }
        public string BankBranch { get; set; }
        public string ProofUpload { get; set; }
        public string ProofFileName { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Student Student { get; set; }
    }
}
