//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnosoftModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeesFollowupHistory
    {
        public int Id { get; set; }
        public int AdmissionId { get; set; }
        public Nullable<System.DateTime> FollowupDate { get; set; }
        public Nullable<int> FacultyId { get; set; }
        public Nullable<System.DateTime> NextFollowupDate { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsDropout { get; set; }
        public string ReasonForDropOut { get; set; }
        public Nullable<bool> IsFollowup { get; set; }
    }
}
