//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnosoftModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasedSerivce
    {
        public int Id { get; set; }
        public int InstituteId { get; set; }
        public int SubscriptionServiceId { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public int Quantity { get; set; }
        public decimal Amount { get; set; }
        public bool IsApprove { get; set; }
        public System.DateTime ApproveDate { get; set; }
        public string Remark { get; set; }
        public System.DateTime RenewalDate { get; set; }
        public bool IsDeleted { get; set; }
        public string Status { get; set; }
    
        public virtual SubscriptionService SubscriptionService { get; set; }
    }
}
