//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnosoftModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RazorPayment
    {
        public int Id { get; set; }
        public int EWalletTransactionId { get; set; }
        public string RazorId { get; set; }
        public string RazorEntity { get; set; }
        public string Amount { get; set; }
        public string Currency { get; set; }
        public string Status { get; set; }
        public string OrderId { get; set; }
        public string Method { get; set; }
        public string Description { get; set; }
        public string CardId { get; set; }
        public string Bank { get; set; }
        public string Wallet { get; set; }
        public string Email { get; set; }
        public string Contact { get; set; }
        public string Fee { get; set; }
        public string ServiceTax { get; set; }
        public string ErrorCode { get; set; }
        public string ErrorDescription { get; set; }
        public string CreatedAt { get; set; }
    
        public virtual EWalletTransation EWalletTransation { get; set; }
    }
}
