//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnosoftModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Admissions = new HashSet<Admission>();
            this.Enquiries = new HashSet<Enquiry>();
            this.FeeReceipts = new HashSet<FeeReceipt>();
        }
    
        public int Id { get; set; }
        public int InstituteId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Email { get; set; }
        public Nullable<int> MotherTongueLanguageId { get; set; }
        public string Mobile { get; set; }
        public string ParentMobile { get; set; }
        public string OtherContact { get; set; }
        public string Address { get; set; }
        public int TalukaId { get; set; }
        public int DistrictId { get; set; }
        public int StateId { get; set; }
        public int CountryId { get; set; }
        public string Pincode { get; set; }
        public Nullable<int> QualificationId { get; set; }
        public System.DateTime AddedDate { get; set; }
        public string Photo { get; set; }
        public string Signature { get; set; }
        public string suburb { get; set; }
        public string AadharNo { get; set; }
        public Nullable<bool> PhysicallyChallenged { get; set; }
        public string MaritalStatus { get; set; }
        public string PhotoFileName { get; set; }
        public string SignFileNAme { get; set; }
        public string Disability { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admission> Admissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enquiry> Enquiries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeeReceipt> FeeReceipts { get; set; }
        public virtual Qualification Qualification { get; set; }
    }
}
