//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnosoftModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public int InstituteId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string MarritalStatus { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public string SalaryType { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string PAN { get; set; }
        public string Aadhar { get; set; }
        public string MobileNo { get; set; }
        public string AlternateMobileNo { get; set; }
        public Nullable<int> QualificationId { get; set; }
        public Nullable<System.DateTime> DateOfJioning { get; set; }
        public Nullable<System.DateTime> DateOfLeaving { get; set; }
        public Nullable<decimal> TransactionLimit { get; set; }
        public Nullable<decimal> CashInHand { get; set; }
        public string CAddress { get; set; }
        public Nullable<int> CStateId { get; set; }
        public Nullable<int> CDistrictId { get; set; }
        public Nullable<int> CTalukaId { get; set; }
        public Nullable<int> CSuburbId { get; set; }
        public string CPinCode { get; set; }
        public string PAddress { get; set; }
        public Nullable<int> PStateId { get; set; }
        public Nullable<int> PDistrictId { get; set; }
        public Nullable<int> PTalukaId { get; set; }
        public Nullable<int> PSuburbId { get; set; }
        public string PPinCode { get; set; }
        public string BankAccountNo { get; set; }
        public string AccountHolderName { get; set; }
        public string BankName { get; set; }
        public string IFSCCode { get; set; }
        public string BankBranch { get; set; }
        public string BankProofUpload { get; set; }
        public Nullable<bool> IsBankProofUpload { get; set; }
        public string PhotoUpload { get; set; }
        public Nullable<bool> IsPhotoUpload { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string PhotpFIleName { get; set; }
        public string BankProofFileName { get; set; }
        public int RoleId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Institute Institute { get; set; }
    }
}
