//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnosoftModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMenuAccess
    {
        public int Id { get; set; }
        public int MenuId { get; set; }
        public int InstituteId { get; set; }
        public int UserId { get; set; }
        public bool Add { get; set; }
        public bool Edit { get; set; }
        public bool View { get; set; }
        public bool Delete { get; set; }
        public bool Print { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual MenuMaster MenuMaster { get; set; }
    }
}
